name: sliver_catalog_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  sliver_catalog:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  mjk_lint_rules: ^3.0.1

flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/test.frag
    - assets/shaders/another_test.frag
    - assets/shaders/gradient.frag
    - assets/shaders/burning.frag
    - assets/shaders/burning_2.frag
    - assets/shaders/freezing.frag
  assets:
    - assets/textures/