name: sliver_catalog
description: A set of various slivers that add custom visual behavior.
version: 0.0.1
homepage: "https://github.com/MbIXjkee/sliver_catalog"
repository: "https://github.com/MbIXjkee/sliver_catalog"
issue_tracker: "https://github.com/MbIXjkee/sliver_catalog/issues"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mjk_lint_rules: ^3.0.1

flutter:
