name: sliver_catalog
description: A collection of experimental and creative slivers for Flutter.
version: 0.1.1
homepage: "https://github.com/MbIXjkee/sliver_catalog"
repository: "https://github.com/MbIXjkee/sliver_catalog"
issue_tracker: "https://github.com/MbIXjkee/sliver_catalog/issues"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
  mjk_lint_rules: ^3.0.1

flutter:
  shaders:
    - assets/shaders/freezing.frag
    - assets/shaders/blood.frag
    - assets/shaders/template.frag
