{
  "sksl": {
    "entrypoint": "freezing_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform vec2 uOffset;\nuniform float uProgress;\nuniform shader uFreezeTexture;\nuniform half2 uFreezeTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_easeOutQuad(float x)\n{\n    return 1.0 - ((1.0 - x) * (1.0 - x));\n}\n\nvoid FLT_main()\n{\n    vec2 xy = FLT_flutter_local_FlutterFragCoord() - uOffset;\n    vec2 uvRect = xy / uSize;\n    float scaleX = uSize.x / 543.0;\n    float scaleY = uSize.y / 360.0;\n    float scale = max(scaleX, scaleY);\n    vec2 factor = vec2(scaleX, scaleY) / vec2(scale);\n    vec2 offset = (vec2(1.0) - factor) * 0.5;\n    vec2 uvCover = (uvRect * factor) + offset;\n    uvCover = clamp(uvCover, vec2(0.0), vec2(1.0));\n    vec4 freezeTex = uFreezeTexture.eval(uFreezeTexture_size * ( uvCover));\n    float mask = dot(freezeTex.xyz, vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625));\n    float freezeStart = 0.0;\n    float freezeEnd = 0.699999988079071044921875;\n    float normalized = clamp((uProgress - freezeStart) / (freezeEnd - freezeStart), 0.0, 1.0);\n    float param = normalized;\n    float freezeThreshold = FLT_flutter_local_easeOutQuad(param);\n    float edgeWidth = 0.100000001490116119384765625;\n    float t = smoothstep(freezeThreshold, freezeThreshold - edgeWidth, mask);\n    float maxAlpha = 0.449999988079071044921875;\n    vec4 iceColor = freezeTex;\n    iceColor.w *= (t * maxAlpha);\n    bvec4 _153 = bvec4(t < 0.00999999977648258209228515625);\n    fragColor = vec4(_153.x ? vec4(0.0).x : iceColor.x, _153.y ? vec4(0.0).y : iceColor.y, _153.z ? vec4(0.0).z : iceColor.z, _153.w ? vec4(0.0).w : iceColor.w);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uOffset",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uProgress",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 3,
        "name": "uFreezeTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}