name: "Tests with coverage"
description: "Runs tests with coverage and uploads the results to Codecov"
runs:
  using: "composite"
  steps:
    - name: Run tests
      run: flutter test --coverage
      shell: bash

    - name: Show coverage summary
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov
        lcov --summary coverage/lcov.info
      shell: bash

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
