name: "Flutter Setup"
description: "Prepares Flutter for using"
runs:
  using: "composite"
  steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Flutter version info
        run: flutter --version
        shell: bash

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-