name: "Upload coverage on changes in main"

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Flutter
        uses: ./.github/actions/flutter-setup

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests and upload coverage
        uses: ./.github/actions/tests-with-coverage
        