name: "Chore after updates in the main branch"

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Update coverage report
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Flutter
        uses: ./.github/actions/flutter-setup

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests and upload coverage
        uses: ./.github/actions/tests-with-coverage
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  deploy-example:
    name: Deploy example to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Flutter
        uses: ./.github/actions/flutter-setup

      - name: Install dependencies
        run: flutter pub get

      - name: Deploy an example
        uses: ./.github/actions/deploy-example
        with:
          destination_dir: latest
          gh_token: ${{ secrets.GITHUB_TOKEN }}
