name: pr_analysis

on:
  pull_request:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check structure
        uses: andstor/file-existence-action@v1
        with:
          files: "lib, test, example, pubspec.yaml, README.md, CHANGELOG.md, LICENSE"
          allow_failure: true

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Flutter version info
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Validate package dependencies
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator

      - name: Run formatter
        run: dart format --set-exit-if-changed .

      - name: Run static code analysis
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run PANA analysis
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  testing:
    needs: analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Flutter version info
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build_android_example:
    needs: testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Flutter version info
        run: flutter --version

      - name: Build Example Android
        run: |
          cd example
          flutter pub get
          flutter build apk

  build_ios_example:
    needs: testing
    runs-on: macos-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build iOS
        run: |
          cd example
          flutter pub get
          flutter build ios --release --no-codesign

  build_web_example:
    needs: testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version info
        run: flutter --version

      - name: Build Example Web
        run: |
          cd example
          flutter pub get
          flutter build web