{
  "sksl": {
    "entrypoint": "custom_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform vec2 uOffset;\nuniform float uProgress;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 xy = FLT_flutter_local_FlutterFragCoord() - uOffset;\n    vec2 uv = xy / uSize;\n    bool _39 = uv.x < 0.0;\n    bool _47;\n    if (!_39)\n    {\n        _47 = uv.x > 1.0;\n    }\n    else\n    {\n        _47 = _39;\n    }\n    bool _55;\n    if (!_47)\n    {\n        _55 = uv.y < 0.0;\n    }\n    else\n    {\n        _55 = _47;\n    }\n    bool _62;\n    if (!_55)\n    {\n        _62 = uv.y > 1.0;\n    }\n    else\n    {\n        _62 = _55;\n    }\n    if (_62)\n    {\n        discard;\n    }\n    vec2 pos = uv * uSize;\n    float stripeCenter = uSize.x * uProgress;\n    float stripeHalfWidth = uSize.x * 0.0199999995529651641845703125;\n    float glowWidth = stripeHalfWidth * 3.0;\n    float dx = pos.x - stripeCenter;\n    float dist = abs(dx);\n    float intensity = exp((-(dist * dist)) / ((2.0 * glowWidth) * glowWidth));\n    intensity *= smoothstep(glowWidth, glowWidth * 0.800000011920928955078125, dist);\n    vec3 lightColor = vec3(1.0, 0.89999997615814208984375, 0.60000002384185791015625);\n    fragColor = vec4(lightColor * intensity, intensity);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uOffset",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uProgress",
        "rows": 1,
        "type": 10
      }
    ]
  }
}